<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="gpsbase" >

  <!-- bring different parts of robots  -->
  <xacro:include filename="$(find rovers_descriptions)/urdf/gpsbase_gazebo.xacro"/>

  <xacro:property name="linking_plate_width" value="2.0"/>
  <xacro:property name="gps_baseplate_height" value="0.03"/>
  <xacro:property name="gps_baseplate_dia" value="0.08"/>
  <xacro:property name="gps_support_height" value="0.5"/>

  <link name="linking_plate">
    <visual>
      <geometry>
        <box size="0.05 ${linking_plate_width} 0.02"/>
      </geometry>
      <material name="black_plastic"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 ${linking_plate_width} 0.2"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.25"/>
      <inertia ixx="1.0e-2" ixy="0.0" ixz="0.0" iyy="1.0e-2" iyz="0.0" izz="1.0e-2"/>
    </inertial>
  </link>
 
  <xacro:macro name="gps_unit" params="name:=gps_sensor" >

    <link name="${name}_baseplate">
      <visual>
        <geometry>
          <cylinder length="${gps_baseplate_height}" radius="${gps_baseplate_dia/2}"/>
        </geometry>
        <material name="black_plastic"/>
      </visual>
      <collision>
        <geometry>
         <cylinder length="${gps_baseplate_height}" radius="${gps_baseplate_dia/2}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.2"/>
        <inertia ixx="1.0e-2" ixy="0.0" ixz="0.0" iyy="1.0e-2" iyz="0.0" izz="1.0e-2"/>
      </inertial>
    </link>

    <link name="${name}_supportbar">
      <visual>
        <geometry>
          <cylinder length="${gps_support_height}" radius="0.015"/>
        </geometry>
        <material name="black_plastic"/>
      </visual>
      <collision>
        <geometry>
         <cylinder length="${gps_support_height}" radius="0.015"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.2"/>
        <inertia ixx="1.0e-2" ixy="0.0" ixz="0.0" iyy="1.0e-2" iyz="0.0" izz="1.0e-2"/>
      </inertial>
    </link>

    <link name="${name}_sphere">
      <visual>
        <geometry>
          <sphere radius="${gps_baseplate_height/2}"/>
        </geometry>
        <material name="black_plastic"/>
      </visual>
      <collision>
        <geometry>
         <cylinder length="${gps_support_height}" radius="0.015"/>
        </geometry>
      </collision>
    </link>

    <joint name="${name}_base2support" type="fixed">
      <parent link="${name}_supportbar"/>
      <child link="${name}_baseplate"/>
      <origin xyz="0 0 ${gps_support_height/2}" rpy="0 0 0"/>
      <axis rpy="0 0 0" xyz="0 0 1"/>
    </joint>

    <joint name="${name}_base2sphere" type="fixed">
      <parent link="${name}_baseplate"/>
      <child link="${name}_sphere"/>
      <origin xyz="0 0 ${gps_baseplate_height/2}" rpy="0 0 0"/>
      <axis rpy="0 0 0" xyz="0 0 1"/>
    </joint>

  </xacro:macro>

  <xacro:gps_unit name="gps_right"/>
  <xacro:gps_unit name="gps_left"/>

  <joint name="gps_right_rover" type="fixed">
    <parent link="linking_plate"/>
    <child link="gps_right_supportbar"/>
    <origin xyz="0 ${-1*linking_plate_width/2} ${gps_support_height/2}" rpy="0 0 0"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
  </joint>

  <joint name="gps_left_rover" type="fixed">
    <parent link="linking_plate"/>
    <child link="gps_left_supportbar"/>
    <origin xyz="0 ${1*linking_plate_width/2} ${gps_support_height/2}" rpy="0 0 0"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
  </joint>

</robot>
